routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\BerkasController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\LogbookController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\NilaiPbsController;
use App\Http\Controllers\NilaiTkjController;
use App\Http\Controllers\NilaiTkroController;
use App\Http\Controllers\PembimbingController;
use App\Http\Controllers\PembimbingLapanganController;
use App\Http\Controllers\PrakerinController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\siprakerin\AbsensiSiswaController;
use App\Http\Controllers\siprakerin\BeritaController as SiprakerinBeritaController;
use App\Http\Controllers\siprakerin\DownloadController;
use App\Http\Controllers\siprakerin\HistoryController;
use App\Http\Controllers\siprakerin\HomeController;
use App\Http\Controllers\siprakerin\LaporanController as SiprakerinLaporanController;
use App\Http\Controllers\siprakerin\LogbookController as SiprakerinLogbookController;
use App\Http\Controllers\siprakerin\MitraController as SiprakerinMitraController;
use App\Http\Controllers\siprakerin\NilaiSiswaController;
use App\Http\Controllers\siprakerin\PendaftaranController;
use App\Http\Controllers\siprakerin\PrakerinController as SiprakerinPrakerinController;
use App\Http\Controllers\siprakerin\ProfilController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\StatusController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/home');
});

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::resource('/register',RegisterController::class);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::resource('/home',HomeController::class);
Route::resource('/berita',SiprakerinBeritaController::class);
Route::resource('/mitra',SiprakerinMitraController::class);

Route::group(['middleware' => ['admin']], function(){
    Route::get('/dashboard', function(){return view('dashboard.index');})->name('dashboard');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/siswa', SiswaController::class);
    Route::resource('/pembimbing-lapangan', PembimbingLapanganController::class);
    Route::resource('/nilai-tkj', NilaiTkjController::class);
    Route::resource('/nilai-tkro', NilaiTkroController::class);
    Route::resource('/nilai-pbs', NilaiPbsController::class);
    Route::resource('/data-guru', GuruController::class);
    Route::resource('/logbook', LogbookController::class);
    Route::resource('/data-prakerin', PrakerinController::class);
    Route::resource('/data-berita', BeritaController::class);
    Route::resource('/data-mitra', MitraController::class);
    Route::resource('/berkas', BerkasController::class);
    Route::resource('/status',StatusController::class);
    Route::resource('/kelas',KelasController::class);
    Route::resource('/data-laporan',LaporanController::class);
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('/ubah-password', 'App\Http\Controllers\ChangePasswordController@showChangePasswordForm')->name('password.change');
    Route::post('/ubah-password', 'App\Http\Controllers\ChangePasswordController@changePassword')->name('password.update');
    Route::resource('/profil',ProfilController::class);
    Route::resource('/daftar-prakerin',PendaftaranController::class);
    Route::resource('/logbooks',SiprakerinLogbookController::class);
    Route::resource('/absensi-siswa',AbsensiSiswaController::class);
    Route::resource('/history',HistoryController::class);
    Route::resource('/download',DownloadController::class);
    Route::resource('/nilai-siswa',NilaiSiswaController::class);
    Route::resource('/laporan-akhir',SiprakerinLaporanController::class);
});

app/Models/Berkas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Berkas extends Model
{
    use HasFactory;
    protected $table = 'berkas';
    protected $guarded = ['id'];
}

app/Http/Controllers/BerkasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Berkas;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BerkasController extends Controller
{

    public function index()
    {
        $berkas = Berkas::paginate(10);
        return view('dashboard.berkas.index',compact('berkas'));
    }

    public function create()
    {
        return view('dashboard.berkas.create');
    }


    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama'=>'required',
            'berkas'=>'required'
        ]);
        if ($request->hasFile('berkas')) {
            $path = $request->file('berkas')->store('berkas');
        }else{
            $path = null;
        }
        Berkas::create([
            'nama'=>$request->nama,
            'link'=>$path
        ]);
        return redirect('/berkas');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $berkas = Berkas::where('id',$id)->get();
        return view('dashboard.berkas.edit',compact('berkas'));
    }

    public function update(Request $request, $id)
    {
        $oldPath =$request->oldPath;
        $validatedData = $request->validate([
            'nama'=>'required',
        ]);
        if ($request->hasFile('berkas')) {
            if ($request->oldImage) {
                Storage::delete($request->oldPath);
            }
            $path = $request->file('berkas')->store('berkas');
        }else{
            $path = $oldPath;
        }
        Berkas::where('id',$id)->update([
            'nama'=>$request->nama,
            'link'=>$oldPath
        ]);
        return redirect('/berkas');
    }

    public function destroy($id)
    {
        Berkas::where('id',$id)->delete();
        return redirect('/berkas')->with('success', 'Data berhasil dihapus');
    }
}

resources/views/dashboard/berkas/create.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  
    <section>
        <form action="/berkas" method="post" enctype="multipart/form-data">
            @csrf
            @method('post')
            <div class="mb-3">
              <label for="nama" class="form-label">Nama Berkas</label> 
              <input type="text" class="form-control" id="nama" name="nama" value="">
            </div>
              <div class="mb-3">
                <label for="berkas" class="form-label">Berkas</label>
                <input type="file" class="form-control" id="berkas" name="berkas">
              </div>    
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </section>


</div>
</div>
@endsection

resources/views/dashboard/berkas/edit.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  
    <section>
        @foreach ($berkas as $data)
        <form action="{{route('berkas.update',$data->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="mb-3">
              <label for="nama" class="form-label">Nama Berkas</label> 
              <input type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}">
            </div> 
            <input type="text" name="oldPath" id="" hidden value="{{$data->link}}">  
            @endforeach
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </section>


</div>
</div>
@endsection

resources/views/dashboard/berkas/index.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')
      <a href="/berkas/create" class="btn btn-primary mb-2"><i class="bi bi-plus-square"></i> Tambah Berkas</a>
  @if(session('success'))
      <div class="alert alert-success">
          {{ session('success') }}
      </div>
  @endif
  @if(session('messageWarning'))
      <div class="alert alert-warning">
          {{ session('messageWarning') }}
      </div>
  @endif
  @isset($berkas)
  <table class="table table-hover">
    <tr>
        <th>No.</th>
        <th>Nama Berkas</th>
        <th>Path/Link</th>
        @can('admin')
          <th colspan="2">Action</th>
        @endcan
    </tr>
    @forelse ($berkas as $data)    
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $data->nama }}</td>
            <td>{{ $data->link}}</td>
            @can('admin')    
              <td>
                <form action="{{ route('berkas.destroy', $data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger" title="Hapus data" onclick="return confirm('Apakah anda yakin ingin menghapus?')"><i class="bi bi-trash3-fill"></i></button>
                </form>            
              </td>
              <td>
                <a href="{{route('berkas.edit',$data->id)}}" class="btn btn-primary" title="edit"><i class="bi bi-pencil"></i></a>            
            </td>
            @endcan
        </tr>
        @empty
    @endforelse
  </table>
  
  {{ $berkas->links() }}
  @endisset



</div>
</div>
@endsection