routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\BerkasController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\LogbookController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\NilaiPbsController;
use App\Http\Controllers\NilaiTkjController;
use App\Http\Controllers\NilaiTkroController;
use App\Http\Controllers\PembimbingController;
use App\Http\Controllers\PembimbingLapanganController;
use App\Http\Controllers\PrakerinController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\siprakerin\AbsensiSiswaController;
use App\Http\Controllers\siprakerin\BeritaController as SiprakerinBeritaController;
use App\Http\Controllers\siprakerin\DownloadController;
use App\Http\Controllers\siprakerin\HistoryController;
use App\Http\Controllers\siprakerin\HomeController;
use App\Http\Controllers\siprakerin\LaporanController as SiprakerinLaporanController;
use App\Http\Controllers\siprakerin\LogbookController as SiprakerinLogbookController;
use App\Http\Controllers\siprakerin\MitraController as SiprakerinMitraController;
use App\Http\Controllers\siprakerin\NilaiSiswaController;
use App\Http\Controllers\siprakerin\PendaftaranController;
use App\Http\Controllers\siprakerin\PrakerinController as SiprakerinPrakerinController;
use App\Http\Controllers\siprakerin\ProfilController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\StatusController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/home');
});

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::resource('/register',RegisterController::class);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::resource('/home',HomeController::class);
Route::resource('/berita',SiprakerinBeritaController::class);
Route::resource('/mitra',SiprakerinMitraController::class);

Route::group(['middleware' => ['admin']], function(){
    Route::get('/dashboard', function(){return view('dashboard.index');})->name('dashboard');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/siswa', SiswaController::class);
    Route::resource('/pembimbing-lapangan', PembimbingLapanganController::class);
    Route::resource('/nilai-tkj', NilaiTkjController::class);
    Route::resource('/nilai-tkro', NilaiTkroController::class);
    Route::resource('/nilai-pbs', NilaiPbsController::class);
    Route::resource('/data-guru', GuruController::class);
    Route::resource('/logbook', LogbookController::class);
    Route::resource('/data-prakerin', PrakerinController::class);
    Route::resource('/data-berita', BeritaController::class);
    Route::resource('/data-mitra', MitraController::class);
    Route::resource('/berkas', BerkasController::class);
    Route::resource('/status',StatusController::class);
    Route::resource('/kelas',KelasController::class);
    Route::resource('/data-laporan',LaporanController::class);
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('/ubah-password', 'App\Http\Controllers\ChangePasswordController@showChangePasswordForm')->name('password.change');
    Route::post('/ubah-password', 'App\Http\Controllers\ChangePasswordController@changePassword')->name('password.update');
    Route::resource('/profil',ProfilController::class);
    Route::resource('/daftar-prakerin',PendaftaranController::class);
    Route::resource('/logbooks',SiprakerinLogbookController::class);
    Route::resource('/absensi-siswa',AbsensiSiswaController::class);
    Route::resource('/history',HistoryController::class);
    Route::resource('/download',DownloadController::class);
    Route::resource('/nilai-siswa',NilaiSiswaController::class);
    Route::resource('/laporan-akhir',SiprakerinLaporanController::class);
});

app/Models/Absensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $table = 'absensi';

    public function siswa()
    {
        return $this->belongsTo(Siswa::class);
    }

    public function pembimbingLapangan()
    {
        return $this->belongsTo(PembimbingLapangan::class);
    }
}

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use App\Models\Absensi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\StoreAbsensiRequest;
use App\Http\Requests\UpdateAbsensiRequest;

class AbsensiController extends Controller
{

    public function index()
    {
        if (Gate::allows('pembimbing-lapangan')) {
            $pembimbing_lapangan = Auth::user()->pembimbingLapangan->first();
            if (!$pembimbing_lapangan) {
                return view('dashboard.absensi.index')->with('messageWarning', 'Maaf, anda bukan pembimbing lapangan');
            }
            $siswas = Siswa::where('pembimbing_lapangan_id', $pembimbing_lapangan->id)->get();
            if ($siswas->isEmpty()) {
                return view('dashboard.absensi.index')->with('message', 'Maaf, anda tidak memiliki mahasiswa bimbingan');
            }
            $absensis = Absensi::where('pembimbing_lapangan_id', $pembimbing_lapangan->id)->paginate(7);
            return view('dashboard.absensi.index', ['absensis' => $absensis]);
        } else {
            $absensis = Absensi::orderBy('tanggal','desc')->paginate(10);
            return view('dashboard.absensi.index', ['absensis' => $absensis]);
        }
    }

    public function create()
    {
        $pembimbing_lapangan = Auth::user()->pembimbingLapangan->first();

        if (!$pembimbing_lapangan) {
            return redirect('/absensi')->with('messageWarning', 'Maaf, anda bukan pembimbing lapangan');
        }
        
        $siswas = Siswa::where('pembimbing_lapangan_id', $pembimbing_lapangan->id)->get();
        if ($siswas->isEmpty()) {
            return redirect('/absensi')->with('messageWarning', 'Maaf, anda tidak memiliki mahasiswa bimbingan');
        }

        return view('dashboard.absensi.create', [
            'siswas' => $siswas,
            'pl' => $pembimbing_lapangan->id
        ]);
    }

    public function store(Request $request)
    {

        $validatedData = $request->validate([
            'siswa' => 'required',
            'ket_kehadiran' => 'required',
            'tanggal' => 'required'
        ]);

        $absensi = new Absensi;
        $absensi->siswa_id = $request->siswa;
        $absensi->pembimbing_lapangan_id = $request->pembimbing_lapangan;
        $absensi->ket_kehadiran = $request->ket_kehadiran;
        $absensi->tanggal = $request->tanggal;
        $absensi->save();

        return redirect()->route('absensi.index')->with('success', 'Data absensi berhasil disimpan');
    }

    public function show(Absensi $absensi)
    {
        //
    }

    public function edit($id)
    {
        $absensis = Absensi::where('id',$id)->get();
        return view('dashboard.absensi.edit', ['absensis' => $absensis]);
    }


    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'siswa' => 'required',
            'ket_kehadiran' => 'required',
            'tanggal' => 'required'
        ]);
        Absensi::where('id',$id)->update([
            'siswa_id'=>$request->siswa_id,
            'pembimbing_lapangan_id'=>$request->pembimbing_lapangan,
            'ket_kehadiran'=>$request->ket_kehadiran,
            'tanggal'=>$request->tanggal,
        ]);
        return redirect('/absensi');
    }

    public function destroy(Absensi $absensi)
    {
        $absensi->delete();
        return redirect('/absensi')->with('success', 'Data absensi berhasil dihapus');
    }
}

resources/views/dashboard/absensi/create.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')


  <form action="/absensi" method="POST">
    @method('post')
    @csrf
    <div>
        <label for="siswa" class="form-label">Siswa: NISN/Nama</label>
        <select class="form-control @error('siswa') is-invalid @enderror" name="siswa">
            @foreach ($siswas as $siswa)
                <option class="text-secondary" value="{{ $siswa->id }}" {{ old('siswa') == $siswa->id ? 'selected' : '' }}>{{ $siswa->user->fullname." / ".$siswa->nisn }}</option>
            @endforeach
        </select>
        @error('siswa')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>
    <div>
        <input type="hidden" value="{{ $pl }}" name="pembimbing_lapangan">
    </div>
    <div class="mb-3">
      <label for="ket_kehadiran" class="form-label">Keterangan Kehadiran</label>
      {{-- <input type="text" value="{{ old('ket_kehadiran') }}" class="form-control @error('ket_kehadiran') is-invalid @enderror" name="ket_kehadiran"> --}}
      <select class="form-select @error('ket_kehadiran') is-invalid @enderror" value="{{ old('impresi') }}" aria-label="Default select example" name="ket_kehadiran">
        <option selected>Pilih kehadiran..</option>
        <option value="Hadir">Hadir</option>
        <option value="Izin">Izin</option>
        <option value="Sakit">Sakit</option>
        <option value="Absen">Absen</option>
      </select>
      @error('ket_kehadiran')
          <div class="invalid-feedback">
              {{ $message }}
          </div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="tanggal" class="form-label">Tanggal</label>
      <input type="date" value="{{ old('tanggal') }}" class="form-control @error('tanggal') is-invalid @enderror" name="tanggal">
      @error('tanggal')
          <div class="invalid-feedback">
              {{ $message }}
          </div>
      @enderror
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


</div>
</div>
@endsection

resources/views/dashboard/absensi/edit.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')

@foreach ($absensis as $absensi)

  <form action="{{route('absensi.update',$absensi->id)}}" method="POST">
    @method('put')
    @csrf
    <div>
        <label for="siswa" class="form-label">Siswa:</label>
        <input type="text" readonly class="form-control" name="siswa" value="{{$absensi->siswa ? $absensi->siswa->user->fullname : 'Data Siswa Ini Telah Dihapus'}}">
        <input type="text" hidden name="siswa_id" value="{{$absensi->siswa_id}}">
        @error('siswa')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>
    <div>
        <input type="hidden" value="{{$absensi->pembimbing_lapangan_id}}" name="pembimbing_lapangan">
    </div>
    <div class="mb-3">
      <label for="ket_kehadiran" class="form-label">Keterangan Kehadiran</label>
      {{-- <input type="text" value="{{ old('ket_kehadiran') }}" class="form-control @error('ket_kehadiran') is-invalid @enderror" name="ket_kehadiran"> --}}
      <select class="form-select @error('ket_kehadiran') is-invalid @enderror" value="{{ old('impresi') }}" aria-label="Default select example" name="ket_kehadiran">
        <option {{$absensi->ket_kehadiran == 'Hadir' ? 'selected' : ''}} value="Hadir">Hadir</option>
        <option {{$absensi->ket_kehadiran == 'Izin' ? 'selected' : ''}} value="Izin">Izin</option>
        <option {{$absensi->ket_kehadiran == 'Sakit' ? 'selected' : ''}} value="Sakit">Sakit</option>
        <option {{$absensi->ket_kehadiran == 'Absen' ? 'selected' : ''}} value="Absen">Absen</option>
      </select>
      @error('ket_kehadiran')
          <div class="invalid-feedback">
              {{ $message }}
          </div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="tanggal" class="form-label">Tanggal</label>
      <input type="date" value="{{$absensi->tanggal}}" class="form-control @error('tanggal') is-invalid @enderror" name="tanggal">
      @error('tanggal')
          <div class="invalid-feedback">
              {{ $message }}
          </div>
      @enderror
    </div>
    @endforeach
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


</div>
</div>
@endsection

resources/views/dashboard/absensi/index.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')


  @can('pembimbing-lapangan')
      <a href="/absensi/create" class="btn btn-primary mb-2"><i class="bi bi-plus-square"></i> Tambah Absen Siswa</a>
  @endcan
  @if(session('success'))
      <div class="alert alert-success">
          {{ session('success') }}
      </div>
  @endif
  @if(session('messageWarning'))
      <div class="alert alert-warning">
          {{ session('messageWarning') }}
      </div>
  @endif

  @isset($absensis)
  <table class="table table-hover">
    <tr>
        <th>No.</th>
        <th>Siswa</th>
        <th>Pembimbing Lapangan</th>
        <th>Keterangan Kehadiran</th>
        <th>Tanggal</th>
        @can('admin')
          <th colspan="2">Action</th>
        @endcan
    </tr>
    @foreach ($absensis as $absensi)    
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{$absensi->siswa ? $absensi->siswa->user->fullname : 'Data Siswa Ini Telah Dihapus'}}</td>
            <td>{{$absensi->pembimbingLapangan ? $absensi->pembimbingLapangan->user->fullname : 'Data Pembimbing Telah Dihapus'}}</td>
            <td>{{ $absensi->ket_kehadiran }}</td>
            <td>{{ $absensi->tanggal }}</td>
            @can('admin')    
              <td>
                <form action="{{ route('absensi.destroy', $absensi->id) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger" title="Hapus data" onclick="return confirm('Apakah anda yakin ingin menghapus?')"><i class="bi bi-trash3-fill"></i></button>
                </form>            
              </td>
              <td>
                <a href="{{route('absensi.edit',$absensi->id)}}" class="btn btn-primary" title="edit"><i class="bi bi-pencil"></i></a>            
            </td>
            @endcan
        </tr>
    @endforeach
  </table>
  {{ $absensis->links() }}
  @endisset



</div>
</div>
@endsection