routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\BerkasController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\LogbookController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\NilaiPbsController;
use App\Http\Controllers\NilaiTkjController;
use App\Http\Controllers\NilaiTkroController;
use App\Http\Controllers\PembimbingController;
use App\Http\Controllers\PembimbingLapanganController;
use App\Http\Controllers\PrakerinController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\siprakerin\AbsensiSiswaController;
use App\Http\Controllers\siprakerin\BeritaController as SiprakerinBeritaController;
use App\Http\Controllers\siprakerin\DownloadController;
use App\Http\Controllers\siprakerin\HistoryController;
use App\Http\Controllers\siprakerin\HomeController;
use App\Http\Controllers\siprakerin\LaporanController as SiprakerinLaporanController;
use App\Http\Controllers\siprakerin\LogbookController as SiprakerinLogbookController;
use App\Http\Controllers\siprakerin\MitraController as SiprakerinMitraController;
use App\Http\Controllers\siprakerin\NilaiSiswaController;
use App\Http\Controllers\siprakerin\PendaftaranController;
use App\Http\Controllers\siprakerin\PrakerinController as SiprakerinPrakerinController;
use App\Http\Controllers\siprakerin\ProfilController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\StatusController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/home');
});

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::resource('/register',RegisterController::class);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::resource('/home',HomeController::class);
Route::resource('/berita',SiprakerinBeritaController::class);
Route::resource('/mitra',SiprakerinMitraController::class);

Route::group(['middleware' => ['admin']], function(){
    Route::get('/dashboard', function(){return view('dashboard.index');})->name('dashboard');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/siswa', SiswaController::class);
    Route::resource('/pembimbing-lapangan', PembimbingLapanganController::class);
    Route::resource('/nilai-tkj', NilaiTkjController::class);
    Route::resource('/nilai-tkro', NilaiTkroController::class);
    Route::resource('/nilai-pbs', NilaiPbsController::class);
    Route::resource('/data-guru', GuruController::class);
    Route::resource('/logbook', LogbookController::class);
    Route::resource('/data-prakerin', PrakerinController::class);
    Route::resource('/data-berita', BeritaController::class);
    Route::resource('/data-mitra', MitraController::class);
    Route::resource('/berkas', BerkasController::class);
    Route::resource('/status',StatusController::class);
    Route::resource('/kelas',KelasController::class);
    Route::resource('/data-laporan',LaporanController::class);
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('/ubah-password', 'App\Http\Controllers\ChangePasswordController@showChangePasswordForm')->name('password.change');
    Route::post('/ubah-password', 'App\Http\Controllers\ChangePasswordController@changePassword')->name('password.update');
    Route::resource('/profil',ProfilController::class);
    Route::resource('/daftar-prakerin',PendaftaranController::class);
    Route::resource('/logbooks',SiprakerinLogbookController::class);
    Route::resource('/absensi-siswa',AbsensiSiswaController::class);
    Route::resource('/history',HistoryController::class);
    Route::resource('/download',DownloadController::class);
    Route::resource('/nilai-siswa',NilaiSiswaController::class);
    Route::resource('/laporan-akhir',SiprakerinLaporanController::class);
});

app/Models/Laporan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Laporan extends Model
{
    use HasFactory;
    protected $table = 'laporan';
    protected $guarded = ['id'];
}

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Laporan;
use App\Models\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class LaporanController extends Controller
{

    public function index()
    {
        $status = Status::get()->value('laporan');
        $laporan = Laporan::orderBy('created_at','desc')->paginate(10);
        return view('dashboard.laporan.index',compact('laporan','status'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $kelas = Kelas::all();
        $laporan = Laporan::where('id',$id)->get();
        return view('dashboard.laporan.edit',compact('laporan','kelas'));
    }

    public function update(Request $request, $id)
    {
        $oldPath =$request->oldPath;
        $validatedData = $request->validate([
            'nama'=>'required',
            'kelas'=>'required',
        ]);
        if ($request->hasFile('file')) {
            if ($oldPath) {
                Storage::delete($oldPath);
            }
            $path = $request->file('file')->store('laporan_akhir');
        }else{
            $path = $oldPath;
        }
        Laporan::where('id',$id)->update([
            'nama'=>$request->nama,
            'kelas'=>$request->kelas,
            'file'=>$oldPath
        ]);
        return redirect('/data-laporan');
    }

    public function destroy($id)
    {
        Laporan::where('id',$id)->delete();
        return redirect('/data-laporan')->with('success', 'Data berhasil dihapus');
    }
}

app/Http/Controllers/siprakerin/LaporanController.php
<?php

namespace App\Http\Controllers\siprakerin;

use App\Http\Controllers\Controller;
use App\Models\Kelas;
use App\Models\Laporan;
use App\Models\Siswa;
use App\Models\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class LaporanController extends Controller
{

    public function index(Request $request)
    {
        $user_id = Auth::user()->id;
        $kls_filter = $request->kls_filter;
        $kelas = Kelas::all();
        $pl_siswa = Siswa::where('user_id',$user_id)->value('pembimbing_lapangan_id');
        $status = Status::get()->value('laporan');
        if (Gate::allows('siswa')) {
           if ($pl_siswa == null) {
            return view('siprakerin-page.laporan.error');
           }else {
            $query = Laporan::query(); 
            $laporan = Laporan::where('user_id',$user_id)->value('user_id');
           
            if ($kls_filter) {
                $query->where('kelas',$kls_filter);
            }
            $laporan_akhir = $query->orderBy('created_at','desc')->paginate(10);
            return view('siprakerin-page.laporan.index',compact('kelas','laporan','laporan_akhir','status','pl_siswa'));
           } 
        }else {
            $query = Laporan::query(); 
            $laporan = Laporan::where('user_id',$user_id)->value('user_id');
           
            if ($kls_filter) {
                $query->where('kelas',$kls_filter);
            }
            $laporan_akhir = $query->orderBy('created_at','desc')->paginate(10);
            return view('siprakerin-page.laporan.index',compact('kelas','laporan','laporan_akhir','status','pl_siswa'));
        }
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $user_id = Auth::user()->id;
        $validatedData = $request->validate([
            'nama'=>'required',
            'kelas'=>'required',
            'file'=>'max:2048'
        ]);
        if ($request->hasFile('file')) {
            $path = $request->file('file')->store('laporan_akhir');
        }else{
            $path = '';
        }
        Laporan::create([
            'nama'=>$request->nama,
            'kelas'=>$request->kelas,
            'user_id'=>$user_id,
            'file'=>$path
        ]);
        return redirect('/laporan-akhir')->with('success','berkas laporan berhasil diupload');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/laporan/edit.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')
  <section>
    @foreach ($laporan as $data)
    <form action="{{route('data-laporan.update',$data->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="mb-3">
          <label for="nama" class="form-label">Nama Siswa</label> 
          <input type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}">
        </div> 
        <div class="mb-3">
          <label for="nama" class="form-label">Kelas</label> 
          <select name="kelas" id="" class="form-select">
            @foreach ($kelas as $kls)
                <option {{$data->kelas == $kls->nama_kelas ? 'selected' : ''}} value="{{$kls->nama_kelas}}">{{$kls->nama_kelas}}</option>
            @endforeach
          </select>
        </div> 
        <input type="text" name="oldPath" id="" hidden value="{{$data->file}}">  
        @endforeach
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</section>


</div>
</div>
@endsection

resources/views/dashboard/laporan/index.blade.php
@extends('dashboard.layouts.main')
@section('container')

<div class="wrapper d-flex align-items-stretch">
  @include('dashboard.layouts.sidebar')

  <!-- Page Content  -->
<div id="content" class="px-4 py-1 p-md-5">
  @include('dashboard.layouts.navbar')
     
  @if(session('success'))
      <div class="alert alert-success">
          {{ session('success') }}
      </div>
  @endif
  @if(session('messageWarning'))
      <div class="alert alert-warning">
          {{ session('messageWarning') }}
      </div>
  @endif
  @isset($laporan)
  <table class="table table-hover">
    <tr>
        <th>No.</th>
        <th>Nama Siswa</th>
        <th>Kelas</th>
        <th>File</th>
        @can('admin')
          <th colspan="2">Action</th>
        @endcan
    </tr>
    @forelse ($laporan as $data)    
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $data->nama }}</td>
            <td>{{ $data->kelas }}</td>
            <td><a href="{{asset('storage/'.$data->file)}}" download="laporan_akhir_{{$data->nama}}" class="btn btn-primary">Download</a></td>
            @can('admin')    
              <td>
                <form action="{{ route('data-laporan.destroy', $data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger" title="Hapus data" onclick="return confirm('Apakah anda yakin ingin menghapus?')"><i class="bi bi-trash3-fill"></i></button>
                </form>            
              </td>
              <td>
                <a href="{{route('data-laporan.edit',$data->id)}}" class="btn btn-primary" title="edit"><i class="bi bi-pencil"></i></a>            
            </td>
            @endcan
        </tr>
        @empty
    @endforelse
  </table>
  
  {{ $laporan->links() }}
  @endisset



</div>
</div>
@endsection