routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\BerkasController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\LogbookController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\NilaiPbsController;
use App\Http\Controllers\NilaiTkjController;
use App\Http\Controllers\NilaiTkroController;
use App\Http\Controllers\PembimbingController;
use App\Http\Controllers\PembimbingLapanganController;
use App\Http\Controllers\PrakerinController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\siprakerin\AbsensiSiswaController;
use App\Http\Controllers\siprakerin\BeritaController as SiprakerinBeritaController;
use App\Http\Controllers\siprakerin\DownloadController;
use App\Http\Controllers\siprakerin\HistoryController;
use App\Http\Controllers\siprakerin\HomeController;
use App\Http\Controllers\siprakerin\LaporanController as SiprakerinLaporanController;
use App\Http\Controllers\siprakerin\LogbookController as SiprakerinLogbookController;
use App\Http\Controllers\siprakerin\MitraController as SiprakerinMitraController;
use App\Http\Controllers\siprakerin\NilaiSiswaController;
use App\Http\Controllers\siprakerin\PendaftaranController;
use App\Http\Controllers\siprakerin\PrakerinController as SiprakerinPrakerinController;
use App\Http\Controllers\siprakerin\ProfilController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\StatusController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/home');
});

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::resource('/register',RegisterController::class);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::resource('/home',HomeController::class);
Route::resource('/berita',SiprakerinBeritaController::class);
Route::resource('/mitra',SiprakerinMitraController::class);

Route::group(['middleware' => ['admin']], function(){
    Route::get('/dashboard', function(){return view('dashboard.index');})->name('dashboard');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/siswa', SiswaController::class);
    Route::resource('/pembimbing-lapangan', PembimbingLapanganController::class);
    Route::resource('/nilai-tkj', NilaiTkjController::class);
    Route::resource('/nilai-tkro', NilaiTkroController::class);
    Route::resource('/nilai-pbs', NilaiPbsController::class);
    Route::resource('/data-guru', GuruController::class);
    Route::resource('/logbook', LogbookController::class);
    Route::resource('/data-prakerin', PrakerinController::class);
    Route::resource('/data-berita', BeritaController::class);
    Route::resource('/data-mitra', MitraController::class);
    Route::resource('/berkas', BerkasController::class);
    Route::resource('/status',StatusController::class);
    Route::resource('/kelas',KelasController::class);
    Route::resource('/data-laporan',LaporanController::class);
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('/ubah-password', 'App\Http\Controllers\ChangePasswordController@showChangePasswordForm')->name('password.change');
    Route::post('/ubah-password', 'App\Http\Controllers\ChangePasswordController@changePassword')->name('password.update');
    Route::resource('/profil',ProfilController::class);
    Route::resource('/daftar-prakerin',PendaftaranController::class);
    Route::resource('/logbooks',SiprakerinLogbookController::class);
    Route::resource('/absensi-siswa',AbsensiSiswaController::class);
    Route::resource('/history',HistoryController::class);
    Route::resource('/download',DownloadController::class);
    Route::resource('/nilai-siswa',NilaiSiswaController::class);
    Route::resource('/laporan-akhir',SiprakerinLaporanController::class);
});

app/Models/Prakerin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Prakerin extends Model
{
    use HasFactory;
    protected $table = 'prakerin';
    protected $guarded = ['id'];
    
}

app/Http/Controllers/PrakerinController.php
<?php

namespace App\Http\Controllers;

use App\Models\Prakerin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PrakerinController extends Controller
{

    public function index()
    {
        $prakerin = Prakerin::all();
        return view('dashboard.prakerin.index',compact('prakerin'));
    }

    public function create()
    {
        return view('dashboard.prakerin.create');
    }

    public function store(Request $request)
    {
        $user_id = Auth::user()->id;
        $validatedData = $request->validate([
            'nama'=>'required',
            'prodi'=>'required',
            'angkatan'=>'required',
            'tahun_ajaran'=>'required',
            'tanggal_mulai'=>'required',
            'tanggal_selesai'=>'required',
            'perusahaan'=>'required',
            'bidang'=>'required',
            'alamat'=>'required',
            'kontak'=>'required',
            'surat'=>'max:2048',
            'bukti'=>'max:2048'
        ]);
        if ($request->hasFile('surat')) {
            $path_surat = $request->file('surat')->store('surat_permohonan');
        }else{
            $path_surat = '';
        }
        if ($request->hasFile('bukti')) {
            $path_bukti = $request->file('bukti')->store('bukti_surat_balasan');
        }else{
            $path_bukti = '';
        }
        Prakerin::create([
            'nama'=>$request->nama,
            'prodi'=>$request->prodi,
            'angkatan'=>$request->angkatan,
            'tahun_ajaran'=>$request->tahun_ajaran,
            'tanggal_mulai'=>$request->tanggal_mulai,
            'tanggal_selesai'=>$request->tanggal_selesai,
            'mitra_perusahaan'=>$request->perusahaan,
            'bidang_mitra'=>$request->bidang,
            'alamat_mitra'=>$request->alamat,
            'kontak_perusahaan'=>$request->kontak,
            'surat_permohonan'=>$path_surat,
            'bukti_diterima'=>$path_bukti,
        ]);
        return redirect('/data-prakerin');
    }

    public function show($id)
    {
        $prakerin = Prakerin::where('id',$id)->get();
        return view('dashboard.prakerin.show', compact('prakerin'));
    }

    public function edit($id)
    {
        $prakerin = Prakerin::where('id',$id)->get();
        return view('dashboard.prakerin.edit',compact('prakerin'));
    }

    public function update(Request $request)
    {
        $old_surat = $request->oldSurat;
        $old_bukti = $request->oldBukti;
        $validatedData = $request->validate([
            'nama'=>'required',
            'prodi'=>'required',
            'angkatan'=>'required',
            'tahun_ajaran'=>'required',
            'tanggal_mulai'=>'required',
            'tanggal_selesai'=>'required',
            'perusahaan'=>'required',
            'bidang'=>'required',
            'alamat'=>'required',
            'kontak'=>'required',
            'surat'=>'max:2048',
            'bukti'=>'max:2048'
        ]);
        if ($request->hasFile('surat')) {
            if ($request->oldSurat) {
                Storage::delete($request->oldSurat);
            }
            $path_surat = $request->file('surat')->store('surat_permohonan');
        }else{
            $path_surat = $old_surat;
        }
        if ($request->hasFile('bukti')) {
            if ($request->oldBukti) {
                Storage::delete($request->oldBukti);
            }
            $path_bukti = $request->file('bukti')->store('bukti_surat_balasan');
        }else{
            $path_bukti = $old_bukti;
        }
        Prakerin::where('id',$request->id)->update([
            'nama'=>$request->nama,
            'prodi'=>$request->prodi,
            'angkatan'=>$request->angkatan,
            'tahun_ajaran'=>$request->tahun_ajaran,
            'tanggal_mulai'=>$request->tanggal_mulai,
            'tanggal_selesai'=>$request->tanggal_selesai,
            'mitra_perusahaan'=>$request->perusahaan,
            'bidang_mitra'=>$request->bidang,
            'alamat_mitra'=>$request->alamat,
            'kontak_perusahaan'=>$request->kontak,
            'surat_permohonan'=>$path_surat,
            'bukti_diterima'=>$path_bukti,
        ]);
        return redirect('/data-prakerin');
    }

    public function destroy($id)
    {
        Prakerin::where('id',$id)->delete();
        return redirect('/data-prakerin')->with('success', 'Data absensi berhasil dihapus');
    }
}

resources/views/siprakerin-page/prakerin/edit.blade.php
@extends('layouts.page')
@section('content')
<div class="row">
    <div class="col" id="prakerin-header">
      <div class="row">
        <div class="col-9">
          <h2 style="font-weight: 600;">Mulai <span style="color:#FF6B00;"> Mimpi Dan Petualanganmu </span> 
            Dengan Mendaftar Prakerin Sekarang Juga!</h2>
          <h4>Jangan sampai terlambat ya..</h4>
        </div>
        <div class="col-3">
          <img id="vector1" class="img-fluid" src="{{asset('images/vector1.png')}}" alt="" srcset="">
        </div>
      </div>
    </div>
</div>
<div class="row">
<div class="col" id="prakerin-page">

    @if (Auth::user()->role->name == 'siswa')
        @if (in_array(Auth::user()->siswa[0]['kelas_id'], [2,5,8]))
        <h3><span>Edit</span> Formulir Pendaftaran</h3>
        <p style="font-size: 14px;">Pastikan data pendaftaran yang akan anda rubah dengan benar!
        </p>
        @foreach ($prakerin as $data)
        <form action="{{route('daftar-prakerin.update',$data->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            <input type="text" hidden name="id" id="" value="{{$data->id}}">
            <input type="text" hidden name="oldImage" value="{{$data->bukti_diterima}}">
            <div class="mb-3">
              <label for="nama" class="form-label">Nama</label> 
              <input type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}">
            </div>
            <div class="mb-3">
                <label for="prodi" class="form-label">Prodi</label> 
                <select class="form-select" aria-label="Default select example" id="prodi" name="prodi">
                    <option {{$data->prodi == 'TKJ' ? 'selected' : ''}} value="TKJ">TKJ</option>
                    <option {{$data->prodi == 'PBS' ? 'selected' : ''}} value="PBS">PBS</option>
                    <option {{$data->prodi == 'TKRO' ? 'selected' : ''}} value="TKRO">TKRO</option>
                  </select>
              </div>
            <div class="mb-3">
                <label for="angkatan" class="form-label">Angkatan</label>
                <input type="text" class="form-control" id="angkatan" name="angkatan" value="{{$data->angkatan}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tahun Ajaran</label>
                <input type="text" class="form-control" id="tahun_ajaran" name="tahun_ajaran" value="{{$data->tahun_ajaran}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Mulai</label>
                <input type="date" class="form-control" id="" name="tanggal_mulai" value="{{$data->tanggal_mulai}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Selesai</label>
                <input type="date" class="form-control" id="" name="tanggal_selesai" value="{{$data->tanggal_selesai}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Diterima di Perusahaan/Mitra</label>
                <input type="text" class="form-control" id="perusahaan" name="perusahaan" value="{{$data->mitra_perusahaan}}">
              </div>
              <div class="mb-3">
                <label for="bidang" class="form-label">Bidang Mitra/Perusahaan</label>
                <input type="text" class="form-control" id="bidang" name="bidang" value="{{$data->bidang_mitra}}">
              </div>
              <div class="mb-3">
                <label for="alamat" class="form-label">Alamat Mitra/Perusahaan</label>
                <input type="text" class="form-control" id="alamat" name="alamat" value="{{$data->alamat_mitra}}">
              </div>    
              <div class="mb-3">
                <label for="kontak" class="form-label">Kontak Perusahaan <span style="font-size: 12px">*Email/Nomor Telepon</span></label>
                <input type="text" class="form-control" id="kontak" name="kontak" value="{{$data->kontak_perusahaan}}">
              </div>
              @if ($data->surat_permohonan)
              <div class="mb-3">
                <label for="bukti" class="form-label">Bukti Diterima <span style="font-size:12px;">*jika ada/tidak wajib</span></label> 
                <input type="file" class="form-control" id="bukti" name="bukti">
              </div>
              @else
              <p>Hanya dapat upload bukti/surat balasan apabila sudah mendapat surat permohonan dari admin</p>
              @endif
              @endforeach
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        @else
            <h2>Maaf Anda Tidak Dapat Mengisi Formulir Karena Bukan Siswa Kelas 11</h2>
        @endif
    @else
        <h1>Maaf Anda Tidak Dapat Mengakses Halaman Ini</h1>
    @endif
    
    </div>
</div>
@endsection

resources/views/siprakerin-page/prakerin/index.blade.php
@extends('layouts.page')
@section('content')
@if ($status == 'buka')
<div class="row">
    <div class="col" id="prakerin-header">
        <div class="row">
          <div class="col-9">
            <h2 style="font-weight: 600;">Mulai <span style="color:#FF6B00;"> Mimpi Dan Petualanganmu </span> 
              Dengan Mendaftar Prakerin Sekarang Juga!</h2>
            <h4>Jangan sampai terlambat ya..</h4>
          </div>
          <div class="col-3">
            <img id="vector1" class="img-fluid" src="{{asset('images/vector1.png')}}" alt="" srcset="">
          </div>
        </div>
    </div>
</div>

  
<div class="row {{$prakerin->where('user_id',Auth::user()->id)->isEmpty() ? 'd-none':'' }}">
    <div class="col" id="prakerin-data">
        <h5><span>{{Auth::user()->nickname}},</span> ini adalah data pendaftaran anda!</h5>
        <p style="font-size:14px;">Apakah terdapat kesalahan pada data anda? kalau ada, langsung diedit ya!</p>
        <table class="table mb-0 text-center table-responsive table-striped table-sm">
            <tr>
              <th>No</th>
              <th>Nama</th>
              <th>Prodi</th>
              <th>Mitra</th>
              <th>Detail</th>
              <th colspan="2">Aksi</th>
            </tr>
            @forelse ($prakerin as $data)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{$data->nama}}</td>
              <td>{{$data->prodi}}</td>
              <td>{{$data->mitra_perusahaan}}</td>
                <td> <a id="bukti" href="{{route('daftar-prakerin.show',$data->id)}}">Lihat detail</a></td>
                <td>
                    <form action="{{ route('daftar-prakerin.destroy',$data->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger" title="Hapus data" onclick="return confirm('Apakah anda yakin ingin menghapus?')"><i class="bi bi-trash3-fill"></i></button>
                    </form>
                <td>
                    <a href="{{route('daftar-prakerin.edit',$data->id)}}" class="btn btn-primary" title="edit"><i class="bi bi-pencil"></i></a>            
                </td>
            </tr>
            @empty  
            @endforelse
        </table>
    </div>
</div>
<div class="row">
<div class="col" id="prakerin-page">

    @if (Auth::user()->role->name == 'siswa')
        @if (in_array(Auth::user()->siswa[0]['kelas_id'], [2,5,8]))
        <h3>Formulir Pendaftaran</h3>
        <p style="font-size: 14px;">Harap memasukkan data pendaftaran dengan benar!
            <br>Dilarang mengisi formulir pendaftaran 2 kali. Kalau ada kesalahan pengisian mohon edit secara mandiri atau menghubungi Admin.
        </p>
        <form action="{{url('/daftar-prakerin')}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('post')
            <div class="mb-3">
              <label for="nama" class="form-label">Nama</label> 
              <input type="text" class="form-control" id="nama" name="nama" value="">
            </div>
            <div class="mb-3">
                <label for="prodi" class="form-label">Prodi</label> 
                <select class="form-select" aria-label="Default select example" id="prodi" name="prodi">
                    <option selected>Pilih Prodi..</option>
                    <option value="TKJ">TKJ</option>
                    <option value="PBS">PBS</option>
                    <option value="TKRO">TKRO</option>
                  </select>
              </div>
            <div class="mb-3">
                <label for="angkatan" class="form-label">Angkatan <span style="font-size: 12px">*ditulis dalam angka</span></label>
                <input type="text" class="form-control" id="angkatan" name="angkatan" value="">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tahun Ajaran</label>
                <input type="text" class="form-control" id="tahun_ajaran" name="tahun_ajaran" value="">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Mulai</label>
                <input type="date" class="form-control" id="" name="tanggal_mulai" value="">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Selesai</label>
                <input type="date" class="form-control" id="" name="tanggal_selesai" value="">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Diterima di Perusahaan/Mitra</label>
                <input type="text" class="form-control" id="perusahaan" name="perusahaan" value="">
              </div>
              <div class="mb-3">
                <label for="bidang" class="form-label">Bidang Mitra/Perusahaan</label>
                <input type="text" class="form-control" id="bidang" name="bidang" value="">
              </div>
              <div class="mb-3">
                <label for="alamat" class="form-label">Alamat Mitra/Perusahaan</label>
                <input type="text" class="form-control" id="alamat" name="alamat" value="">
              </div>    
              <div class="mb-3">
                <label for="kontak" class="form-label">Kontak Perusahaan <span style="font-size: 12px">*Email/Nomor Telepon</span></label>
                <input type="text" class="form-control" id="kontak" name="kontak" value="">
              </div>
            <button type="submit" class="btn btn-primary" id="btn-submitdaftar">Daftar</button>
          </form>
        @else
            <h2>Maaf Anda Tidak Dapat Mengisi Formulir Karena Bukan Siswa Kelas 11</h2>
        @endif
    @else
    <div class="text-center">
        <img src="{{asset('images/closed.png')}}" class="img-fluid"  alt="">
        <h5>Maaf Anda Tidak Dapat Mengakses Halaman Ini Karena Anda Bukan Siswa</h5>
    </div>
    @endif
    
    </div>
</div>
@else
    <div class="row">
      <div class="col text-center mt-5">
        <img src="{{asset('images/closed.png')}}" class="img img-fluid" alt="">
        <h2 style="color:gray;">Oops.. Pendaftaran Sedang Ditutup Nih</h2>
      </div>
    </div>
@endif
@endsection

resources/views/siprakerin-page/prakerin/show.blade.php
@extends('layouts.page')
@section('content')
<div class="row">
    <div class="col" id="prakerin-header">
      <div class="row">
        <div class="col-9">
          <h2 style="font-weight: 600;">Mulai <span style="color:#FF6B00;"> Mimpi Dan Petualanganmu </span> 
            Dengan Mendaftar Prakerin Sekarang Juga!</h2>
          <h4>Jangan sampai terlambat ya..</h4>
        </div>
        <div class="col-3">
          <img id="vector1" class="img-fluid" src="{{asset('images/vector1.png')}}" alt="" srcset="">
        </div>
      </div>
    </div>
</div>
<div class="row">
<div class="col" id="prakerin-page">

        @foreach ($prakerin as $data)
        <form action="{{route('daftar-prakerin.update',$data->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            <input type="text" hidden name="id" id="" value="{{$data->id}}">
            <input type="text" hidden name="oldImage" value="{{$data->bukti_diterima}}">
            <div class="mb-3">
              <label for="nama" class="form-label">Nama</label> 
              <input readonly type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}">
            </div>
            <div class="mb-3">
                <label for="prodi" class="form-label">Prodi</label> 
                <select disabled class="form-select" aria-label="Default select example" id="prodi" name="prodi">
                    <option {{$data->prodi == 'TKJ' ? 'selected' : ''}} value="TKJ">TKJ</option>
                    <option {{$data->prodi == 'PBS' ? 'selected' : ''}} value="PBS">PBS</option>
                    <option {{$data->prodi == 'TKRO' ? 'selected' : ''}} value="TKRO">TKRO</option>
                  </select>
              </div>
            <div class="mb-3">
                <label for="angkatan" class="form-label">Angkatan</label>
                <input readonly type="text" class="form-control" id="angkatan" name="angkatan" value="{{$data->angkatan}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tahun Ajaran</label>
                <input readonly type="text" class="form-control" id="tahun_ajaran" name="tahun_ajaran" value="{{$data->tahun_ajaran}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Mulai</label>
                <input readonly type="date" class="form-control" id="" name="tanggal_mulai" value="{{$data->tanggal_mulai}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Tanggal Selesai</label>
                <input readonly type="date" class="form-control" id="" name="tanggal_selesai" value="{{$data->tanggal_selesai}}">
              </div>
              <div class="mb-3">
                <label for="perusahaan" class="form-label">Diterima di Perusahaan/Mitra</label>
                <input readonly type="text" class="form-control" id="perusahaan" name="perusahaan" value="{{$data->mitra_perusahaan}}">
              </div>
              <div class="mb-3">
                <label for="bidang" class="form-label">Bidang Mitra/Perusahaan</label>
                <input readonly type="text" class="form-control" id="bidang" name="bidang" value="{{$data->bidang_mitra}}">
              </div>
              <div class="mb-3">
                <label for="alamat" class="form-label">Alamat Mitra/Perusahaan</label>
                <input readonly type="text" class="form-control" id="alamat" name="alamat" value="{{$data->alamat_mitra}}">
              </div>    
              <div class="mb-3">
                <label for="kontak" class="form-label">Kontak Perusahaan <span style="font-size: 12px">*Email/Nomor Telepon</span></label>
                <input readonly type="text" class="form-control" id="kontak" name="kontak" value="{{$data->kontak_perusahaan}}">
              </div>
              <div class="mb-3">
                <label for="kontak" class="form-label">Surat Permohonan</label>
                @if ($surat == null)
                <input readonly placeholder="Belum Memiliki Surat - Menunggu surat dari admin" type="text" class="form-control" id="kontak" name="surat" value="">
                @else
                    <a href="{{asset('storage/'.$data->surat_permohonan)}}" download="surat_permohonan_{{$data->nama}}" class="btn btn-primary">Download surat permohonan</a>
                @endif  
              </div>
              <div class="mb-3">
                <label for="bukti" class="form-label">Bukti Diterima <span style="color:red; font-size:12px;">*jika ada/tidak wajib</span></label>
                @if ($data->bukti_diterima == null)
                <input readonly placeholder="Belum Memiliki Bukti/Surat Balasan - mohon upload bukti di halaman edit bila sudah mendapatkannya" type="text" class="form-control" id="kontak" name="bukti" value="">
                @else
                <a href="{{asset('storage/'.$data->bukti_diterima)}}" download="surat_balasan_{{$data->nama}}" class="btn btn-primary">Download bukti/surat balasan</a>
                @endif
              </div> 
              @endforeach
          </form>
    
    </div>
</div>
@endsection